name: Setup docker

description: Configure the docker workflow.

inputs:
  DOCKERHUB_USERNAME:
    required: true
  DOCKERHUB_TOKEN:
    required: true
  QUAY_USERNAME:
    required: true
  QUAY_TOKEN:
    required: true
  CR_PAT:
    required: true
  tag:
    required: true

outputs:
  tags:
    description: "tags"
    value: ${{ steps.meta.outputs.tags }}
  labels:
    description: "labels"
    value: ${{ steps.meta.outputs.labels }}

runs:
  using: composite
  steps:
    - name: Docker meta:${{ inputs.tag }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ inputs.DOCKERHUB_USERNAME }}/fc2-live-dl,ghcr.io/${{ github.repository_owner }}/fc2-live-dl,quay.io/${{ github.repository_owner }}/fc2-live-dl
        flavor: |
          latest=${{ inputs.tag == 'alpine' }}
        tags: |
          type=ref,event=tag,enable=${{ inputs.tag == 'alpine' }}
          type=ref,suffix=-${{ inputs.tag }},event=tag
          ${{ inputs.tag }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    # Create a Access Token and save it as as Actions secret
    # https://hub.docker.com/settings/security
    # DOCKERHUB_USERNAME
    # DOCKERHUB_TOKEN
    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.DOCKERHUB_USERNAME }}
        password: ${{ inputs.DOCKERHUB_TOKEN }}

    # Create a Access Token with `read:packages` and `write:packages` scopes
    # CR_PAT
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ inputs.CR_PAT }}

    - name: Login to Quay Container Registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ inputs.QUAY_USERNAME }}
        password: ${{ inputs.QUAY_TOKEN }}
